name: SFDX Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Salesforce SFDX CLI Action
        # You may pin to the exact commit or the version.
        # uses: sfdx-actions/setup-sfdx@d6a953fdfe15e4d05ca910870457536a36dc60fe
        uses: sfdx-actions/setup-sfdx@v1
        with:
          # Authorize a Salesforce org using an SFDX auth URL
          sfdx-auth-url: ${{ secrets.DEVHUB_URL }}
      
      - name: Set Default DevHub
        run: sfdx force:config:set defaultdevhubusername=mandradesf@protonmail.com
      
      - name: Run a one-line script
        run: echo Hello World
        
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
